export const icons = {
  close: require('./icons/close.png'),
  mom: require('./icons/mom.png'),
  rightArrow: require('./icons/right-arrow.png'),
  bag: require('./icons/bag.png'),
  leftArrow: require('./icons/arrow-left.png'),
  momOval: require('./icons/mom-oval.png'),
  momBaby: require('./icons/mom-baby.png'),
  books: require('./icons/books.png'),
  more: require('./icons/more.png'),
  deleteTrash: require('./icons/delete-trash.png'),
  visibility: require('./icons/visibility.png'),
  edit: require('./icons/edit.png'),
  checkPurple: require('./icons/check-icon-purple.png'),
  addPlusWhite: require('./icons/add-plus-white.png'),
  addPlusPurple: require('./icons/add-plus-purple.png'),
};
